### ISSUE TITLE
[Feature Request]: Add an `/about` page

### ISSUE THREAD

**Issue by Qubik65536** [iXORTech/RemoteMC-MCDR#13]
### Please choose if applies:

- [X] I'm currently working on a adding this feature.

### Describe the solution you'd like

Add an /about page to show the current RemoteMC-MCDR version number, built number, built date, dependencies' version, etc.

### Anything else?

- This should be done **only after** #12 was completed.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/iXORTech/RemoteMC-MCDR/issues) and this has not been posted before

**Comment by Cubik65536** [comment]
This is canceled due to #31
